"""Shared language assets: section names, disclaimers, tier phrasing.

Kept separate so the LLM backend (and the guardrail validator) speak with one
voice and share the same safety guarantees.
"""
from __future__ import annotations

SECTIONS = [
    "What we found",
    "What may be contributing",
    "What this means",
    "What to do next",
    "When to seek care urgently",
]

DISCLAIMER = (
    "This summary is generated by a computer model to help you understand your "
    "health information. It is not a diagnosis and not a substitute for advice "
    "from a qualified clinician. Always talk to your healthcare provider about "
    "your results and any decisions."
)

# Cautious, non-diagnostic phrasing per risk tier.
TIER_PHRASE = {
    "low": "a lower estimated chance",
    "moderate": "a moderate estimated chance",
    "elevated": "a higher estimated chance",
}

CONFIDENCE_PHRASE = {
    "higher": "The model is relatively confident in this estimate",
    "moderate": "The model has moderate confidence in this estimate",
    "lower": "The model is less certain about this estimate, so please treat it with extra caution",
}

# Generic, non-prescriptive next steps. These are educational prompts to discuss
# with a clinician, never treatment instructions.
GENERIC_NEXT_STEPS = [
    "Consider sharing this summary with your doctor or care team at your next visit.",
    "Keep up with any regular check-ups, medications, and monitoring your clinician has recommended.",
    "Ask your care team which, if any, of the factors below you can act on.",
]

# Standard, widely-recognised urgent-care guidance (not tailored diagnosis).
URGENT_CARE_GUIDANCE = [
    "Chest pain or pressure, severe shortness of breath, or fainting.",
    "Sudden weakness, numbness, trouble speaking, or a severe sudden headache.",
    "Confusion, a very high fever you can't control, or symptoms that get rapidly worse.",
    "Any symptom that feels like an emergency — when in doubt, contact emergency services.",
]

# Phrases the output must never contain (overclaiming / diagnosis). Used by the
# guardrail validator.
BANNED_PHRASES = [
    "you have ",
    "you will ",
    "you are going to ",
    "diagnosed with",
    "you definitely",
    "is certain",
    "guaranteed",
    "i diagnose",
    "you must take",
    "stop taking",
    "no need to see",
]
